= Spring Bootを導入するときにやったこと
:toc: left
:toc-title: 目次
:auther: 中島慎児
:source-highlighter: coderay

メンバーの未経験率が高いテクノロジーをスムーズに導入するにはどうするか。

== はじめに（メンバーのレベルなど）

Java8で、link:https://projects.spring.io/spring-boot/[Spring Boot]を使ったシステムを構築した際に、実施したこと、気を付けたことなどを共有する。 +
チーム規模は8人程度で、Javaの基本的なスキルは問題なく、ただしフレームワークの Spring Boot はほぼ初めてという状態からのスタート。

== 事前準備編

事前に考慮すべきことは以下のように想定した。

. 実行環境の確認
. 手順書の準備
. 開発環境をそろえる
. ビルドはIDEに依存しないようにする。
. コーディング規約はできるだけ自動で
. パッケージの切り方を決める
. サンプルコードを書く

=== 実行環境の確認

まず最初に、本番環境の構成を確認する。 +

ポイントは、ネットワークの構成、ファイヤーウォールやロードバランサーの位置、アプリケーションサーバの構成、関連する別サーバや外部サービスの有無、データベースの構成など。 +
特にアプリケーションサーバの構成は必ず確認する。 +

てっきり１台のみとおもいこんで設計を進めると、あとから「いや2台構成で上流にロードバランサーがいるんですよ」などと言われて大慌てすることになる。 +
1台のみで独立している場合と、複数台構成でいつでも切り替えられるようにする場合では、かなりソフトウェアの構造が変わってくる。 +
Webアプリケーションの場合は、複数台構成ではまず、セッションをどこに格納するのかの検討が必要になる。 +
検討結果によって、ネットワーク構成の中にlink:https://redis.io/[Redis]などのKey Value Storeを導入するか、セッションデータを登録するテーブルをデータベースに設けるなどの、作成しようとしているJavaシステム外部での対処が必要になる。 +
どちらにしても仕組みを後から導入するのはかなり骨が折れる。 +

=== 手順書の準備

手順書（やその他のドキュメントなど）はテキストベースにする。理由は、迅速な作成と更新と閲覧のため。 +

ドキュメントは気を付けないと容易に腐る。 +
最終的な納品物は体裁を気にする必要もあるが、チーム内で流通する情報は鮮度が命である。 +

コツとしては、何かしらドキュメントを作成しなければならない場合に、可能であれば要求される前に作って共有する。 +
まとまった資料として要求されると、かならず資料作成に入る前に資料の見栄えに関する要求が暗黙の裡に入ってくる。たとえばExcelで作ってくれとか。 +
そうなる前に、markdownやasciidocなどの見栄えをコントロールできるテキストファイルでドキュメントを作ってしまうと、意外と受け入れられやすい。 +

=== 開発環境をそろえる

チームメンバーの開発環境は可能な限りそろえる。 +


=== スケルトンを作る手順を公開する

モダンなフレームワークにはたいてい、Railsでいうscaffoldのような、最初の一歩を生成する手段がある。 +
Spring Boot でいうなら、link:https://start.spring.io[SPRING INITIALIZR]がある。 +
チームメンバーの理解を促すために、 +


=== ビルドはIDEに依存しないようにする（CIを視野に入れる）

=== コーディング規約は、できるだけ自動で

=== パッケージの切り方を決める

=== サンプルコードを書く（ことで、フレームワークを先行して理解する）

== 開発基盤構築編

開発基盤を構築する際の考慮すべき点。

. lombokを使う
. 現在日時は１箇所に集める
. local,develop,production環境きりわけ
. ログ出力
. 親クラスを作る
. 排他制御を作る
. 認証
. 監査証跡

=== lombokを使う

=== 現在日時は１箇所に集める

=== local,develop,production環境きりわけ

=== ログ出力

=== 親クラスを作る

=== 排他制御を作る

=== 認証

=== 監査証跡

== できていないこと

=== 汎用的な認証と認可

=== テストを作る

==== テストデータの持ち方

==== DB構造の配布と同期

=== ライブラリの選定（サロゲートキーとActiveRecord形式が蛇蝎のごとく嫌われている）

=== Reactの理解

=== スケールするかどうかの考慮ができていない　複数アプリサーバとかRedisとか
